all: hanoi

hanoi: hanoi.o primlib.o
	gcc -fsanitize=undefined -g $^ -o $@  -lSDL2_gfx `sdl2-config --libs` -lm

.c.o: 
	gcc -fsanitize=undefined -g -Wall -pedantic `sdl2-config --cflags` -c  $<

primlib.o: primlib.c primlib.h

hanoi.o: hanoi.c primlib.h

clean:
	-rm primlib.o hanoi.o hanoi
